name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
env:
  PROJECT_ID: ${{ secrets.G_PROJECT_ID }}
  IMAGE: ridgelist
  SERVICE: ridgelist-ci
  
jobs:


  build:
    environment: ci
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Checkout
        run: cd RidgeList.FrontEnd && npm install
      - name: Cypress.io
        # You may pin to the exact commit or the version.
        # uses: cypress-io/github-action@6e6d77eeb1dda289679ea46f13aff1ec4d879d55
        uses: cypress-io/github-action@v2.7.0
        with:
          # Sends test results to Cypress Dashboard
          record: false
          # Set configuration values. Separate multiple values with a comma. The values set here override any values set in your configuration file.
          config: baseUrl=https://ridgelist-ci-gfhqqojama-nw.a.run.app
          # Path to a JSON file where configuration values are set.
          config-file: cypress.json
          # Sets Cypress environment variables
          browser: chrome
          # Command that overrides cypress run
#          command: # optional
          # Command for starting local server in the background
#          start: # optional
          # A different start command on Windows
#          start-windows: # optional
          # Command to run in build step before starting tests
#          build: # optional
          # Whether or not to run install
          install: true
          # Custom install command to use
#          install-command: # optional
          # Whether or not to run tests
#          runTests: # optional
          # Local server URL to wait for
#          wait-on: # optional
          # Amount of time to wait for wait-on url to be available
#          wait-on-timeout: # optional
          # Whether or not to load balance tests using multiple containers
#          parallel: # optional
          # Group setting for tests
#          group: # optional
          # Tag setting for tests
#          tag: # optional
          # Working directory containing Cypress folder
          working-directory: RidgeList.FrontEnd
          # Whether or not to use headless mode
          headless: true
          # Provide a specific specs to run
#          spec: # optional
          # Path of project to run
#          project: # optional
          # You can prefix the default test command using the command-prefix option.
#          command-prefix: # optional
          # ID associates multiple CI machines to one test run
#          ci-build-id: # optional
          # Custom cache key
#          cache-key: # optional
          # Whether or not to silence any Cypress specific output from stdout
#          quiet: # optional
    
#    - name: Set up gcloud Cloud SDK environment
#      uses: google-github-actions/setup-gcloud@v0.2.0
#      with:
#        service_account_key: ${{ secrets.GCLOUD_AUTH }}
#        project_id: ${{ env.PROJECT_ID }}
#        export_default_credentials: true
#        
#    - name: GCloud Docker auth
#      run: gcloud auth configure-docker
#    
#    - uses: actions/checkout@v2
#    - name: Build the Docker image
#      run: docker build . --file RidgeList.FrontEnd/Dockerfile --tag "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA"
#     
#    - name: Push the Docker image
#      run: docker push "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA"
#    
#    - name: Deploy to cloud run
#      run: gcloud run deploy ${{ env.SERVICE }} --image="gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA" --platform=managed --region=europe-west2 --port=80 --allow-unauthenticated --set-env-vars=[ASPNETCORE_ENVIRONMENT=ci]
#      
